In [3]:
import numpy as np
import time

In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seasonds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start} seasonds")




python list time = 0.24898648262023926 seasonds
numpy array time = 0.007749795913696289 seasonds


In [5]:
#memory 
import sys

print(f"python list size = {sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
numpy array size = 8000000 bytes


In [8]:
import numpy as np

In [10]:
#creat - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.shape)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [8]:
#creat - numpy array from scratch 
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

#range(start, end, step)
arr5 = np.arange(0,11,2) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 3) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [26]:
import numpy as np

arr1 = np.zeros((2,3), dtype = "int64")
print(arr1, arr1.shape)

arr2 = np.ones(10,)
print(arr2, arr2.shape)

arr3 = np.full((3,4), 190)
print(arr3, arr3.shape)

arr3 = np.full((2,3), 900)
print(arr3, arr3.shape)

arr4 = np.eye(3)
print( arr4, arr4.shape)

arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

arr6 = np.linspace(1,200, 3)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
[[190 190 190 190]
 [190 190 190 190]
 [190 190 190 190]] (3, 4)
[[900 900 900]
 [900 900 900]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  100.5 200. ] (3,)


In [9]:
#properties
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape)  #dimenstions= m x n
print(arr.size)  #tot els -9
print(arr.dtype)  

float_arr= arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [10]:
#operations on arrays

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [28]:
arr = np.array([[1,2,3], [4,5,6]])
reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [29]:
#indexing
#arr = np.array([1,2,3,4,5])
arr = np.array([[1,2,3], [4,5,6]]) # 1,2,3 is row 1 and 4,5,6 is row 2, means arr[0] is 1,2,3 arr[1] is 4,5,6 and 2 means 4 idx is 0,5 idx is 1 and 6 idx is 2  

print(arr[1][2])


6


In [12]:
#Fancy Indexing 
arr = np.array([1,2,3,4,5])

idx = [1,3,4]
print(arr[idx])

[2 4 5]


In [13]:
#boolean indexing
arr = np.array([1,2,3,4,5])

print(arr[arr > 2])
print(arr[arr % 2 ==0])
print(arr[arr %2 !=0])

 


[3 4 5]
[2 4]
[1 3 5]


In [30]:
#copy vs view
#nums=[1,2,3,4,5]
#sub_list= nums[1:3]
#print(sub_list)
#sub_list[0]=200

#print(sub_list)
#print(nums)

op = [1,2,3,4,5]
sub_list = op[1:3]
print(op)
sub_list[0]=400

print(sub_list)
print(op)

[1, 2, 3, 4, 5]
[400, 3]
[1, 2, 3, 4, 5]


In [15]:
#data types
#complex nums
arr1 = np.array([3 + 5j])
arr2 = np.array([9 + 4j])

print(arr1 + arr2)
print(arr1 - arr2)

[12.+9.j]
[-6.+1.j]


In [16]:
#multi-dimentional arrays

arr2D = np.array([[1,2,3,], [4,5,6], [7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [25]:
#3D array

arr3D = np.array([[[1,2], [3,4],[5,6]], [[7,8], [9,10], [11,12]]])

print(arr3D, arr3D.shape)

#indexcing
print(arr3D[1,1,0])

#slicing
arr3D[:,0,:]=99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [27]:
#vectorization

arr = np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr ** 2)
print(arr + 10)
print( arr +arr2)


[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [32]:
#broadcasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr + arr2)
print(arr.shape)
print(arr2.shape)


[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(5,)
(2, 5)


In [38]:
#normalize

arr = np.array([[1,2], [3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [41]:
#mathematical fnx
#Aggregation

arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))  #return index of min like 0th index we have 1
print(np.argmax(arr))  #return index of max like 4th index we have 5
print(np.mean(arr))
print(np.std(arr)) # formula is (x-mean)squre of 2
print(np.median(arr))  #in sorted order it gives middle one like 3
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [43]:
#power fnx

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [47]:
#log

arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [50]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14)) # round up we use ceil fnx give upper val
print(np.floor(3.14)) # round down we use floor fnx give lower val
print(np.trunc(3.14)) 

3.0
4.0
3.0
3.0


In [56]:
#unique fnx
arr = np.array([1,-3,4,5,-8,9,3,-4])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) #abs fnx for absuloute values make negetive val positive

[-8 -4 -3  1  3  4  5  9]
[-8 -4 -3  1  3  4  5  9]
[1 3 4 5 8 9 3 4]
